schema_version: 1
frequency: 30
glove:
  type: psiglove_2
  side: left
  port: /dev/serial/by-id/usb-PsiBot_SynGlove_336F344F3333-if00
  baudrate: 115200
retargeting:
  type: wuji_tier2
  mapping_file: ../../../third_party/rlinf-dexhand/configs/calibrations/psiglove_2_left_mapping.yaml
  scale_file: ../../../third_party/rlinf-dexhand/configs/calibrations/wuji_left_scale.yaml
hand:
  type: wuji1hand
  side: left
rviz_test:
  endpoint: tcp://127.0.0.1:5557
  timeout_ms: 500
