defaults: [dexjoco_lamp_dp_il_decoder_only_hammer_nail, _self_]
runner: {logger: {experiment_name: dexjoco_lamp_dp_il_mlp_hammer_nail}}
actor: {model: {hand_prior: {type: mlp, latent_dim: 6, artifact_path: null}}}
