defaults:
  - dexjoco_lamp_il_base
  - _self_

runner:
  max_steps: 30000
  logger:
    experiment_name: dexjoco_lamp_prior_vq_click_mouse

data:
  task_name: click_mouse
  dataset_root: ./datasets/DexJoCo-Datasets-LeRobot/dexjoco_lerobot_datasets
  cache_root: ./outputs/lamp_cache

actor:
  global_batch_size: 256
  micro_batch_size: 256
  model:
    hand_prior:
      type: vq
      latent_dim: 1
      code_latent_dim: 256
      hidden_dim: 512
