defaults: [dexjoco_lamp_dp_il_decoder_only_pinch_tongs, _self_]
runner: {logger: {experiment_name: dexjoco_lamp_dp_il_vq_pinch_tongs}}
actor: {model: {hand_prior: {type: vq, latent_dim: 1, artifact_path: ./outputs/dexjoco_lamp_prior_vq_pinch_tongs/artifact}}}
