defaults: [dexjoco_lamp_dp_il_decoder_only_hammer_nail, _self_]
runner: {logger: {experiment_name: dexjoco_lamp_dp_il_decoder_only_water_plant}}
data: {task_name: water_plant}
algorithm: {bc_loss: {hand: 0.0}}
actor:
  optim:
    lr: 1.0e-4
    warmup_steps: 1000
    weight_decay: 1.0e-3
    backbone_lr_ratio: 0.03
  model:
    hand_prior:
      latent_dim: 2
      artifact_path: ./outputs/lamp_water_plant_base_ckpts/water_plant_prior_cvae_z2_selected/artifact
