defaults: [dexjoco_lamp_prior_cvae_dim6_pinch_tongs, _self_]
runner: {logger: {experiment_name: dexjoco_lamp_prior_cvae_dim2_selected_pinch_tongs}}
actor: {model: {hand_prior: {latent_dim: 2, posterior_kl_weight: 1.0e-4, prior_kl_weight: 3.0e-4}}}
