defaults:
  - dexjoco_lamp_il_base
  - _self_

runner:
  max_steps: 1
  local_update_steps: 1
  save_interval: 1
  logger:
    experiment_name: dexjoco_lamp_prior_pca_dim6_pick_bucket

data:
  task_name: pick_bucket
  dataset_root: ./datasets/DexJoCo-Datasets-LeRobot/dexjoco_lerobot_datasets
  cache_root: ./outputs/lamp_cache

actor:
  torch_compile: false
  model:
    hand_prior:
      type: pca
      latent_dim: 6
