defaults:
  - dexjoco_lamp_dp_il_mlp_pick_bucket
  - _self_

runner:
  logger:
    experiment_name: dexjoco_lamp_dp_il_pca_click_mouse

data:
  task_name: click_mouse

actor:
  model:
    hand_prior:
      type: pca
      latent_dim: 2
      artifact_path: ./outputs/dexjoco_lamp_prior_pca_dim2_click_mouse/artifact
