defaults: [dexjoco_lamp_dp_il_decoder_only_hammer_nail, _self_]
runner: {logger: {experiment_name: dexjoco_lamp_dp_il_cvae_hammer_nail}}
actor: {model: {hand_prior: {type: cvae, latent_dim: 2, artifact_path: ./outputs/lamp_cvae_rerun/dexjoco_lamp_prior_cvae_dim2_selected_hammer_nail/artifact}}}
