runner:
  max_steps: 1
  local_update_steps: 1
  save_interval: 1
  logger:
    experiment_name: dexjoco_lamp_prior_pca_dim2_fold_glasses
data:
  task_name: fold_glasses
  dataset_root: ./datasets/DexJoCo-Datasets-LeRobot/dexjoco_lerobot_datasets
  cache_root: ./outputs/lamp_cache
actor:
  torch_compile: false
  model:
    hand_prior:
      type: pca
      latent_dim: 2
defaults:
- dexjoco_lamp_il_base
- _self_
