defaults: [dexjoco_lamp_dp_il_decoder_only_water_plant, _self_]
runner: {logger: {experiment_name: dexjoco_lamp_dp_il_vq_water_plant}}
actor: {model: {hand_prior: {type: vq, latent_dim: 1, artifact_path: ./outputs/lamp_water_plant_base_ckpts/water_plant_prior_vq/artifact}}}
