defaults:
  - dexjoco_lamp_dp_il_mlp_pick_bucket
  - _self_

runner:
  logger:
    experiment_name: dexjoco_lamp_dp_il_cvae_fold_glasses

data:
  task_name: fold_glasses

actor:
  model:
    hand_prior:
      type: cvae
      latent_dim: 6
      artifact_path: ./outputs/dexjoco_lamp_prior_cvae_dim6_fold_glasses/artifact
