defaults: [dexjoco_lamp_dp_il_decoder_only_pick_bucket, _self_]
runner: {logger: {experiment_name: dexjoco_lamp_dp_il_cvae_pick_bucket}}
actor: {model: {hand_prior: {type: cvae, latent_dim: 6, artifact_path: ./outputs/dexjoco_lamp_prior_cvae_dim6_pick_bucket/artifact}}}
