runner:
  max_steps: 30000
  logger:
    experiment_name: dexjoco_lamp_dp_il_pca_fold_glasses
cluster:
  component_placement:
    actor: 1-1
algorithm:
  stage: dp
data:
  task_name: fold_glasses
  dataset_root: ./datasets/DexJoCo-Datasets-LeRobot/dexjoco_lerobot_datasets
  cache_root: ./outputs/lamp_cache
actor:
  global_batch_size: 512
  micro_batch_size: 512
  eval_batch_size: 512
  optim:
    lr: 3.0e-05
    warmup_steps: 1000
  model:
    model_type: lamp_dp
    hand_prior:
      type: pca
      latent_dim: 2
      artifact_path: ./outputs/dexjoco_lamp_prior_pca_dim2_fold_glasses/artifact
defaults:
- dexjoco_lamp_dp
- _self_
