defaults: [dexjoco_lamp_dp_il_decoder_only_water_plant, _self_]
runner: {logger: {experiment_name: dexjoco_lamp_dp_il_ae_water_plant}}
actor: {model: {hand_prior: {type: ae, latent_dim: 2, artifact_path: ./outputs/lamp_water_plant_base_ckpts/water_plant_prior_ae_z2/artifact}}}
