defaults:
  - dexjoco_lamp_prior_vq
  - _self_

runner:
  logger:
    experiment_name: dexjoco_lamp_prior_vq_water_plant

data:
  task_name: water_plant
  dataset_root: ./datasets/DexJoCo-Datasets-LeRobot/dexjoco_lerobot_datasets
  cache_root: ./outputs/lamp_cache
