defaults:
  - dexjoco_lamp_prior_cvae
  - _self_

runner:
  max_steps: 20000
  logger:
    log_path: ./outputs/lamp_cvae_rerun
    experiment_name: dexjoco_lamp_prior_cvae_dim6_click_mouse

cluster:
  component_placement:
    actor: 0-0

data:
  task_name: click_mouse
  dataset_root: ./datasets/DexJoCo-Datasets-LeRobot/dexjoco_lerobot_datasets
  cache_root: ./outputs/lamp_cache

actor:
  model:
    hand_prior:
      latent_dim: 6
