runner:
  max_steps: 30000
  logger:
    log_path: ./outputs/lamp_dp_rerun
    experiment_name: dexjoco_lamp_dp_il_mlp_pinch_tongs
cluster:
  component_placement:
    actor: 0-0
algorithm:
  stage: dp
data:
  task_name: pinch_tongs
  dataset_root: ./datasets/DexJoCo-Datasets-LeRobot/dexjoco_lerobot_datasets
  cache_root: ./outputs/lamp_cache
actor:
  global_batch_size: 512
  micro_batch_size: 512
  eval_batch_size: 512
  optim:
    lr: 3.0e-05
    warmup_steps: 1000
  model:
    model_type: lamp_dp
    hand_prior:
      type: mlp
      latent_dim: 6
      artifact_path: null
defaults:
- dexjoco_lamp_dp
- _self_
