defaults:
  - dexjoco_lamp_il_base
  - _self_

runner:
  max_steps: 30000
  logger:
    experiment_name: dexjoco_lamp_prior_cvae_dim6_fold_glasses

cluster:
  component_placement:
    actor: 0-0

data:
  task_name: fold_glasses
  dataset_root: ./datasets/DexJoCo-Datasets-LeRobot/dexjoco_lerobot_datasets
  cache_root: ./outputs/lamp_cache

actor:
  global_batch_size: 256
  micro_batch_size: 256
  model:
    hand_prior:
      type: cvae
      latent_dim: 6
      hidden_dim: 1024
      posterior_kl_weight: 1.0e-4
      prior_kl_weight: 1.0e-4
