defaults:
  - dexjoco_lamp_il_base
  - _self_

runner:
  max_steps: 20000
  logger:
    experiment_name: dexjoco_lamp_bc

algorithm:
  stage: bc

actor:
  model:
    model_type: lamp_bc
    num_action_chunks: 1
    hand_prior:
      type: vae
      latent_dim: 3
      artifact_path: ../results/dexjoco_lamp_prior_vae/artifact

rollout:
  model:
    model_type: lamp_bc
