defaults:
  - dexjoco_lamp_dp_il_mlp_pick_bucket
  - _self_

runner:
  logger:
    experiment_name: dexjoco_lamp_dp_il_cvae_click_mouse

data:
  task_name: click_mouse

actor:
  model:
    hand_prior:
      type: cvae
      latent_dim: 2
      artifact_path: ./outputs/lamp_cvae_rerun/dexjoco_lamp_prior_cvae_dim2_selected_click_mouse/artifact
