defaults: [dexjoco_lamp_dp_il_decoder_only_pick_bucket, _self_]
runner: {logger: {experiment_name: dexjoco_lamp_dp_il_pca_pick_bucket}}
actor: {model: {hand_prior: {type: pca, latent_dim: 6, artifact_path: ./outputs/dexjoco_lamp_prior_pca_dim6_pick_bucket/artifact}}}
