defaults:
  - env/realworld_dex_pnp@env.eval
  - collection/ruiyan
  - override hydra/job_logging: stdout
  - _self_

hydra:
  run:
    dir: .
  output_subdir: null
  searchpath:
    - file://${oc.env:EMBODIED_PATH}/config/

runner:
  task_type: embodied
  logger:
    log_path: null
    project_name: rlinf
    experiment_name: "collect-ruiyan-dexhand-data"
    logger_backends: ["tensorboard"] # wandb, swanlab
  num_data_episodes: 20
  record_task_description: False
