defaults:
  - realworld_lamp_il
  - _self_
algorithm:
  stage: dp
actor:
  model:
    hand_prior:
      type: pca
      artifact_path: ???
runner:
  logger:
    experiment_name: realworld_lamp_dp_pca
